[package]
name = "keyper"
version = "0.1.0"
edition = "2021"
readme = "README.md"
repository = "https://github.com/Raforawesome/keyper"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[profile.release]
strip = true
