[package]
name = "perky"
version = "0.1.0"
edition = "2021"
readme = "README.md"
repository = "https://github.com/Raforawesome/perky"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dictionaries = { git = "https://github.com/Raforawesome/dictionaries-rs" }

[profile.release]
strip = true
